### ISSUE TITLE
Introductory text for language-archives site

### ISSUE THREAD

**Issue by marcolarosa** [marcolarosa/pdsc-language-archives.services#1]
@nthieberger 

I'm building out the placeholder site; styled similarly to the coedl site. Screenshot following:
<img width="1679" alt="screen shot 2018-08-29 at 10 49 28 am" src="https://user-images.githubusercontent.com/2639995/44759302-a954c700-ab7c-11e8-867a-3c2d36ae6faa.png">

Could you please provide a paragraph or two of intro text about what this site is for and how it ties in to the main coedl work? I've made a start but as you can see in the screenshot but not really sure how to tie in to the main work.

**Comment by nthieberger** [comment]
to facilitate community access to primary records at the same time as
curating them for research purposes. On this site we provide a
visualisation of records in the world's language archives based on the Open
Language Archives Community service. This gives links to what records are
available for each language.

[is that enough?]

**Comment by marcolarosa** [comment]
It'll do for now. We can always rework once the site is online.
